spring:
   application:
      name: gateway-server
   config:
      import: optional:configserver:http://localhost:8071
   cloud:
      gateway:
         server:
            webflux:
               globalcors:
                  add-to-simple-url-handler-mapping: true
                  corsConfigurations:
                     '[/**]':
                        allowedOrigins: 'http://localhost:5173'
                        allowedMethods:
                        - GET
                        - POST
                        - OPTIONS
                        allowedHeaders: '*'
                        exposedHeaders:
                        - Authorization
logging:
   level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.optimagrowth: DEBUG