const:
    service-owner: 1st
spring:
    application:
        name: servicefirst
#    profiles:
#        active:
#            - dev     
    config:
        import: "optional:configserver:http://59.29.224.126:8888"
server:
   port: 8081        
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://59.29.224.126:9999/eureka/
    instance: 
        preferIpAddress: true 