spring:
   application:
      name: member-service
   config:
      import: optional:configserver:http://localhost:8071
   datasource:
      url: jdbc:postgresql://localhost:5432/ostock_dev
      username: postgres
      password: postgres # '{cipher}8f56ef6d8f583fac6ef2723537be7752b31045ae5983707ec154f55ea3a225a6'
   jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
         ddl-auto: update
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8070/eureka/
   instance:
      preferIpAddress: true
      
token:
   expirationTime: 86400000
   secret: "My JWTToken's Secret is p@ssw0rd"