spring:
   application:
      name: config-server
   profiles:
#     active: native
      active: git
   cloud:
      config:
         server:
            native:
#              search-locations: classpath:/config
               search-locations: file:///c:\temp\config
            git:
               uri: https://github.com/myanjini/spring-config.git
               search-paths: 
                  - licenseservice
                  - eurekaserver
server:
   port: 8071
encrypt:
   key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo