spring:
  application:
    name: license-service
  profiles:
    active:
    - dev     
  config:
    import: "optional:configserver:http://localhost:8071"
server:
  port: 8081

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 10
        event-consumer-buffer-size: 10
        register-health-indicator: true
      licenseService:
        base-config: default
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 5000
resilience4j.retry:
  instances:
    retryLicenseService:
      max-attempts: 5
      waitDuration: 10000ms
      retry-exceptions:
      - java.util.concurrent.TimeoutException
resilience4j.ratelimiter:
  instances:
    licenseService:
      timeoutDuration: 1000ms
      limitRefreshPeriod: 5000
      limitForPeriod: 5

      