spring:
   application:
      name: organization-service
   profiles: 
      active: dev
   config:
      import: "optional:configserver:http://localhost:8071"
server:
   port: 8081   
logging:
  level:
    '[org.springframework.web]': WARN
    '[com.optimagrowth]': DEBUG